name: dailybait
channels:
  - conda-forge
  - defaults
dependencies:
  - fastapi
  - uvicorn[standard]
  - httpx
  - pydantic
  - openai
  - sqlalchemy
  - jinja2
  - typer
  - gunicorn 
  - pip
  - pip:
      - python-dotenv
      - requests
